# Generated by Django 5.0.4 on 2024-12-07 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='county',
        ),
        migrations.AlterField(
            model_name='event',
            name='conference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='district',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
