# Generated by Django 5.0.4 on 2024-12-09 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_event_county_alter_event_conference_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenueImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='venue_images')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('venue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='venue_images', to='events.venue')),
            ],
            options={
                'verbose_name_plural': 'Venue Images',
            },
        ),
    ]
