# Generated by Django 5.0.4 on 2024-12-09 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_venueimages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venue',
            old_name='image1',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='image3',
        ),
        migrations.AlterField(
            model_name='venueimages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/venue'),
        ),
    ]
