# Generated by Django 5.0.4 on 2024-12-09 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_remove_venue_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='type',
        ),
        migrations.AlterField(
            model_name='venue',
            name='county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='venues', to='events.county'),
        ),
    ]
