# Generated by Django 5.0.4 on 2024-12-09 21:35

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_remove_venue_type_alter_venue_county'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='image',
            field=models.ImageField(blank=True, default='./defaults/speaker/profile.PNG', null=True, upload_to='uploads/speakers'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
