# Generated by Django 5.0.4 on 2024-12-09 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_speaker_image_alter_venue_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='image',
            field=models.ImageField(blank=True, default='./images/defaults/speaker/profile.PNG', null=True, upload_to='uploads/speakers'),
        ),
    ]
