# Generated by Django 5.0.4 on 2024-12-09 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_alter_speaker_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchorgroup',
            name='youtube_link',
            field=models.CharField(blank=True, max_length=255, verbose_name='youtube link'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/speakers'),
        ),
    ]
