# Generated by Django 5.0.4 on 2024-12-10 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_conference_union_remove_event_conference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='starting_time',
            field=models.TimeField(blank=True),
        ),
    ]
