# Generated by Django 5.0.4 on 2024-12-11 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_speaker_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_speakers', to='events.event'),
        ),
        migrations.AlterField(
            model_name='sponsorpartner',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_sponsors_partners', to='events.event'),
        ),
        migrations.CreateModel(
            name='PhotoGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/gallery')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_gallery', to='events.event')),
            ],
        ),
    ]
