# Generated by Django 5.0.4 on 2024-12-29 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_event_is_virtual'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='virtual_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
