# Generated by Django 5.0.4 on 2024-12-29 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_event_virtual_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestChoir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/guest_choirs')),
                ('name', models.CharField(max_length=100)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guest_choirs', to='events.event')),
            ],
        ),
    ]
