# Generated by Django 5.0.4 on 2024-12-29 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_guestchoir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestchoir',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_guest_choirs', to='events.event'),
        ),
    ]
