# Generated by Django 5.0.4 on 2024-12-07 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'ordering': ('-created_at',), 'verbose_name_plural': 'contact us'},
        ),
    ]
