# Generated by Django 5.0.4 on 2024-12-01 17:46

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=50)),
                ('postal_address', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('ig_link', models.CharField(blank=True, max_length=255)),
                ('fb_link', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', tinymce.models.HTMLField(null=True)),
                ('icon', models.CharField(blank=True, default='bi-person-gear', max_length=100)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('profile_image', models.ImageField(blank=True, upload_to='uploads/profile')),
                ('position', models.CharField(max_length=100)),
                ('linkedin_link', models.CharField(blank=True, max_length=255)),
                ('ig_link', models.CharField(blank=True, max_length=255)),
                ('fb_link', models.CharField(blank=True, max_length=255)),
                ('x_link', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, upload_to='uploads/about/group_logos')),
                ('fb_link', models.CharField(blank=True, max_length=255, verbose_name='facebook link')),
                ('ig_link', models.CharField(blank=True, max_length=255, verbose_name='instagram link')),
                ('tiktok_link', models.CharField(blank=True, max_length=255)),
                ('x_link', models.CharField(blank=True, max_length=255, verbose_name='x link')),
                ('banner_image', models.ImageField(blank=True, upload_to='uploads/about/banner')),
                ('description', tinymce.models.HTMLField(null=True)),
                ('services_intro', tinymce.models.HTMLField(null=True)),
                ('contacts', models.ManyToManyField(blank=True, to='about.contact')),
                ('services', models.ManyToManyField(blank=True, to='about.services')),
                ('team', models.ManyToManyField(blank=True, to='about.teammember')),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testimonial', models.TextField()),
                ('name', models.CharField(max_length=50)),
                ('organization', models.CharField(max_length=50)),
                ('about', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials', to='about.about')),
            ],
        ),
    ]
