# Generated by Django 5.0.4 on 2024-12-07 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name_plural': 'about'},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'ordering': ('name',), 'verbose_name_plural': 'services'},
        ),
    ]
